### ISSUE TITLE
Link from draft ZEP to discussion

### ISSUE THREAD

**Issue by ivirshup** [zarr-developers/zeps#21]
Could the rendered draft ZEP (e.g. https://zarr.dev/zeps/draft/ZEP0003.html) have a link to the discussion of the ZEP?

Would be nice to have a bidirectional link between the full proposal and its discussion.

**Comment by MSanKeys963** [comment]
Hi @ivirshup.
Yeah, sure. The discussion link can be placed under the `Discussion` section of the draft ZEP.

**Comment by ivirshup** [comment]
I'm wondering if it could go very visibly at the top, similar to how PEP's will have a link to where discussions should happen at the top ([example](https://peps.python.org/pep-3156/))

**Comment by MSanKeys963** [comment]
Hmm, it makes sense to have it on the top. Can you add the link for the discussion at the top?
