### ISSUE TITLE
Proposal to switch to weekly ZEP meetings from bi-weekly routine until ZEP0001 is finalised

### ISSUE THREAD

**Issue by MSanKeys963** [zarr-developers/zeps#29]
Hi all.

During the last week's meeting, I proposed to have weekly ZEP meetings until [ZEP0001](https://zarr.dev/zeps/draft/ZEP0001.html) is finalised.

Among all, I, @jbms, @joshmoore and @jstriebel favour doing this. We're considering having the meeting same time (18:00 CET) every Thursday. This may go on for a few weeks, and then we can switch back to our bi-weekly routine once [ZEP0001](https://zarr.dev/zeps/draft/ZEP0001.html) is finalised.

I believe we should pursue this idea as [ZEP0001](https://zarr.dev/zeps/draft/ZEP0001.html) has been pending for a long time, and the Zarr Community has been looking forward to it. 

Please let me know your thoughts. You can vote by 👍🏻 and 👎🏻.

Note: The change in the community calendar will take effect after the ZEP meeting on 26th January. Check the community calendar [here](https://zarr.dev/zeps/meetings/).

CC: @zarr-developers/implementation-council @zarr-developers/steering-council @DennisHeimbigner

**Comment by jbms** [comment]
To confirm, we will have a ZEP meeting on 2023-01-19?

**Comment by jakirkham** [comment]
Think this is a bit short notice for making the change (if it is intended for today). AIUI next week would be the ZEP meeting. So this could be intended for 2 weeks from now (2 February 2023)

**Comment by joshmoore** [comment]
I'll miss as well. But maybe @jstriebel and @jbms can make the most of not having others distract them :smile:

**Comment by jakirkham** [comment]
That's true. Sorry didn't mean to discourage Jonathan & Jeremy from meeting if they find that helpful

**Comment by MSanKeys963** [comment]
Hi everyone. Thank you for showing interest by upvoting.
Let me reply to the comments above.

> To confirm, we will have a ZEP meeting on 2023-01-19?

@jbms: No. The idea for this issue is to get the interest of having weekly ZEP meetings from the community, schedule the meetings from 2nd February onwards and announce the change in the calendar during the next ZEP meeting, which is on 26th January. Apologies for not making it clear in the issue's description.


> Think this is a bit short notice for making the change (if it is intended for today). AIUI next week would be the ZEP meeting. So this could be intended for 2 weeks from now (2 February 2023)

@jakirkham: Yes, exactly.

> I'll miss as well. But maybe @jstriebel and @jbms can make the most of not having others distract them 😄

@joshmoore: It'd be good if @jbms and @jstriebel can lead the meeting today, but I think it'd be better and in the community's interest, if all of us could join the meeting, including the Zarr Steering Council, which I don't see happening today.

I apologise again for not making it clear in the description. The ZEP and Steering council meetings have a conflict today, which we'll be resolving today itself. And from next week onwards, we can move ahead with the weekly plan.

**Comment by MSanKeys963** [comment]
We've scheduled weekly ZEP meetings until March 2023 to finalise [ZEP0001](https://zarr.dev/zeps/draft/ZEP0001.html).
You can view them here: https://zarr.dev/zeps/meetings/.

Thanks everyone, for your input.
