### ISSUE TITLE
Opengraph metadata is not generated dynamically for each page

### ISSUE THREAD

**Issue by rabernat** [zarr-developers/zeps#4]
Having proper [opengraph metadata](https://ogp.me/) is very important for linking to content on social media. It allows sites like twitter and facebook to generate "cards" for links.

The current Zep site exposes open-graph metadata, but it appears to be non-specific. For example, on https://zarr.dev//zeps/zeps/draft/ZEP0001.html, we get the following (from https://developers.facebook.com/tools/debug/?q=https%3A%2F%2Fzarr.dev%2F%2Fzeps%2Fzeps%2Fdraft%2FZEP0001.html)

| property | value |
|--|--|
| og:url | https://zarr.dev/zeps/zeps/draft/ZEP0001.html |
| og:type | website |
| og:title | ZEP0001 |
| og:locale | { "locale": "en_us" } |
| og:description | Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description. |
| og:site_name | ZEP |
| og:updated_time | 1653745818 |

If I share this website on twitter, it will look like this:

![image](https://user-images.githubusercontent.com/1197350/170828486-1fed41a4-28ae-4b7b-99d9-af7e11b941d9.png)

(via https://cards-dev.twitter.com/validator)

It would be ideal if the description field could be populated correctly somehow. This page contains some information about how to do that: https://jekyll.github.io/jekyll-seo-tag/usage/

**Comment by MSanKeys963** [comment]
Thanks for pointing this out @rabernat. I've fixed this in #5.
