### ISSUE TITLE
Add LICENSE file

### ISSUE THREAD

**Issue by jakirkham** [zarr-developers/zeps#6]
Currently we don't have a license file here. Would be good to add one.

**Comment by jakirkham** [comment]
Personally would suggest [CC0]( https://creativecommons.org/share-your-work/public-domain/cc0/ ). IOW as permissive as possible while still being a license.

**Comment by MSanKeys963** [comment]
Thanks for bringing this up @jakirkham.
What do you think about other licenses like [MIT](https://opensource.org/licenses/MIT) or [GNU](https://www.gnu.org/licenses/gpl-3.0.en.html)?

**Comment by jakirkham** [comment]
Permissive would be fine. Would avoid GPL
